---

name: build-check
on: [push, pull_request]
jobs:
  build-check:
    name: Run build-check on Go ${{ matrix.go }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go:
          - '1.15'
          - '1.14'
          - '1.13'
          - '1.12'
          - '1.11'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make build_check
  save-test-coverage:
    name: Save test coverage
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Get test coverage
        run: make tests
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
